<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonTaskList</name>
   <tag></tag>
   <elementGuidId>31e1ff4c-a752-436a-8678-3947ff6d2e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='v-pills-tab']/button[@id='tasklist-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='v-pills-tab']/button[@id='tasklist-tab']</value>
      <webElementGuid>814eebdd-fa62-4dd7-ada7-164073d848e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>020fda6f-e5fc-47fb-a783-186fddbe36ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
