<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAdd</name>
   <tag></tag>
   <elementGuidId>3acd5f60-49d5-48a5-8b1f-ce3cb5909f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='addnewlist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='addnewlist']</value>
      <webElementGuid>9b742fd6-57f0-4bcc-8c25-ecabd721d524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bff3f33-efbe-4cab-bf91-9db0d3c1744a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
