<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textAreaRichRextNote</name>
   <tag></tag>
   <elementGuidId>697d79b3-66e4-42ea-9728-cad636bc1a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='editor']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='editor']/p</value>
      <webElementGuid>79d5bb33-6fb9-4576-b737-df00e82a2f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a26d456b-6cfb-4fa6-8d51-01542383de45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
